apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: couchdb
  namespace: couchdb
spec:
  defaultBackend:
    service:
      name: couchdb
      port:
        number: 5984
  ingressClassName: tailscale
  tls:
    - hosts:
        - couchdb

