apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - actualbudget-ingress.yaml
  - argocd-server-ingress.yaml
  - couchdb-ingress.yaml
  - home-assistant-ingress.yaml
  - longhorn-ingress.yaml
