apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - actualbudget-ingress.yaml
  - argocd-server-ingress.yaml
  - couchdb-ingress.yaml
  - couchdb-secret.json
  - home-assistant-ingress.yaml
  - longhorn-ingress.yaml
  - datadog-secret.json
  - metallb-annoucment.yaml
  - metallb-pool.yaml
